### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by zek** [voryx/WampPost#15]
I got Error 500: Internal Server Error when I call
curl -H "Content-Type: application/json" \
   -d '{"procedure": "com.server.order.status"}' \
   http://127.0.0.1:8181/

When I inspect the code little bit I printed the error

  #message: "Too few arguments to function WampPost\WampPost::handleRequest(), 1 passed in /Users/zack/Sites/app/vendor/react/http/src/Io/MiddlewareRunner.php on line 49 and exactly 2 expected"

**Comment by mbonneau** [comment]
@zek - Thanks for the catch. This is fixed in the just-release 0.2.1.
