### ISSUE TITLE
Installation out the box fails - "Your requirements could not be solved"

### ISSUE THREAD

**Issue by nightowl77** [voryx/WampPost#2]
Hi 

Thank you for this great piece of code. It is a game changer for me in terms of hooking up legacy systems via simple rest calls to new realtime systems.  Your solution is by far the most elegant and does not come with houndreds of dependancies. 

Just one small problem. voryx/thryway 0.3.x-dev does not exist as defined by composer.json

The output I get in installation is 
- Installation request for voryx/wamppost dev-master -> satisfiable by voryx/wamppost[dev-master].
  - voryx/wamppost dev-master requires voryx/thruway 0.3.x-dev -> no matching package found.

**Comment by mbonneau** [comment]
Hi @nightowl77 ,

Because it relies on a dev branch of Thruway, you have to install that first, or at the same time.

I just tried `composer require voryx/thruway:dev-master` and then `composer require voryx/wamppost:dev-master`. and that worked.

Let me know if this works for you.

**Comment by nightowl77** [comment]
Thank you so much @mbonneau - that did the trick :)

**Comment by mbonneau** [comment]
@nightowl77 - Hopefully we will tag a 0.3 release soon so that it won't be necessary.
