### ISSUE TITLE
Help configuring port in online server

### ISSUE THREAD

**Issue by nahuelhds** [voryx/WampPost#3]
Hi! 

This is not an error of the component, which works great and I'm very thankful for it as it's very nice, really.

I'd need some guidance with my process of going online with it. The issue is:

I'm using WampPost and particularly I'm running the serverWithClient.php file in order to do both server functions and send HTTP requests in other points of the app.
At javascript level I'm using autobahn.js. When working on localhost everything goes fine. Now I'm trying to go online and I cannot make it work.

I don't know if it is something with the javascript, the php or the port configs.

The ws file is located at //[root]/ws/bin/serverWithClient.php. In there, I use port 8181 for WampPost and 9090 for the router.

My javascript runs in //[root]/www/assets/js/notifications.js and it does the following in order to connect:

var connection = new autobahn.Connection({url: 'ws://[serverDomain]:9090/', realm: '[realmName]'})

Where serverDomain is the site's domain and realmName is just that: the realm name (in the example is realm1).

Now, in my centos server I tried the to open both 9090 and 8181 ports. I did the following (at console):

> > iptables -A INPUT -p tcp --dport 9090 -j ACCEPT
> > iptables -A INPUT -p tcp --dport 8181 -j ACCEPT

Then I've saved the iptable configuration and restarted the iptables in order to apply the changes. Finally, in the console again, I start the ws server as I do in localhost, by doing:

> > php /[root]/ws/bin/serverWithClient.php

The server starts fine, but then I go to the address and the browser says that the connection is refused.

I think that what's wrong is the server config, but I really don't know. I'm lost here, so if you could guide me a little would be nice.

Thanks in advance and, again, very nice component you made!

**Comment by nahuelhds** [comment]
I add the following: I've checked if the ports are listening and I did "netstat -tulpn | less" and I see:

tcp        0      0 127.0.0.1:9090              0.0.0.0:\*                   LISTEN      10693/php
tcp        0      0 127.0.0.1:8181              0.0.0.0:\*                   LISTEN      10693/php

So I assume that both ports are being listened. I don't know why the client connections to ws:// are being refused.

Thanks again

**Comment by davidwdan** [comment]
In `serverWithClient.php` are you binding the router to 0.0.0.0 or some other IP address?

**Comment by nahuelhds** [comment]
in both client and router, I'm using 127.0.0.1. Should I try with 0.0.0.0 ?

**Comment by davidwdan** [comment]
Yes, try `0.0.0.0`.  `127.0.0.1` is a loopback, so it's only accessible from localhost.

**Comment by nahuelhds** [comment]
That did the trick! Thank you very much. It's the second time you help me. I'm very glad with you guys. Thank you very much, seriously
