### ISSUE TITLE
Typo probably prevents options from working

### ISSUE THREAD

**Issue by leda-ferreira** [voryx/WampPost#9]
I believe there is a typo on [line 99](https://github.com/voryx/WampPost/blob/master/src/WampPost/WampPost.php#L99) of file /src/WampPost/WampPost.php:

``` php
$options = isset($json->options) && is_object($json->opitons) ? $json->options : null;
```

It should be:

``` php
$options = isset($json->options) && is_object($json->options) ? $json->options : null;
```

**Comment by mbonneau** [comment]
Thanks for catching this.

**Comment by leda-ferreira** [comment]
I just noticed, this happens at [line 128](https://github.com/voryx/WampPost/blob/master/src/WampPost/WampPost.php#L128) also.
